# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_num', models.SmallIntegerField(null=True)),
                ('mem_size', models.SmallIntegerField(null=True)),
                ('rootfs_size', models.SmallIntegerField(null=True)),
                ('disk_desc', models.TextField(max_length=500, null=True)),
                ('nfs_desc', models.TextField(max_length=500, null=True)),
                ('host_role', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100, unique=True)),
                ('work_ip', models.CharField(max_length=30, null=True)),
                ('manage_ip', models.CharField(max_length=30, null=True)),
                ('store_ip', models.CharField(max_length=30, null=True)),
                ('map_ip', models.CharField(max_length=30, null=True)),
                ('os', models.CharField(max_length=20)),
                ('machine_type', models.CharField(max_length=15)),
                ('in_proj', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HWSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_spec', models.TextField(max_length=500, null=True)),
                ('mem_spec', models.TextField(max_length=500, null=True)),
                ('host_model', models.CharField(max_length=100, null=True)),
                ('host_serial_num', models.CharField(max_length=100, null=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostinfo.Hosts')),
            ],
        ),
        migrations.CreateModel(
            name='UserPasswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_passwd', models.CharField(max_length=50, null=True)),
                ('user01', models.CharField(max_length=50, null=True)),
                ('user01_passwd', models.CharField(max_length=50, null=True)),
                ('user02', models.CharField(max_length=50, null=True)),
                ('user02_passwd', models.CharField(max_length=50, null=True)),
                ('user03', models.CharField(max_length=50, null=True)),
                ('user03_passwd', models.CharField(max_length=50, null=True)),
                ('user04', models.CharField(max_length=50, null=True)),
                ('user04_passwd', models.CharField(max_length=50, null=True)),
                ('user05', models.CharField(max_length=50, null=True)),
                ('user05_passwd', models.CharField(max_length=50, null=True)),
                ('user06', models.CharField(max_length=50, null=True)),
                ('user06_passwd', models.CharField(max_length=50, null=True)),
                ('user07', models.CharField(max_length=50, null=True)),
                ('user07_passwd', models.CharField(max_length=50, null=True)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostinfo.Hosts')),
            ],
        ),
        migrations.AddField(
            model_name='hostcap',
            name='host_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostinfo.Hosts'),
        ),
    ]
