# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100, unique=True)),
                ('work_ip', models.CharField(max_length=30, null=True)),
                ('manage_ip', models.CharField(max_length=30, null=True)),
                ('store_ip', models.CharField(max_length=30, null=True)),
                ('map_ip', models.CharField(max_length=30, null=True)),
                ('os', models.CharField(max_length=20)),
                ('machine_type', models.CharField(max_length=15)),
                ('in_proj', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
